//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosOsel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Id { get; set; }
        public string Codigo_Pintura { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Calidad { get; set; }
        public string Tamano { get; set; }
        public string Acabado { get; set; }
        public string Tipo { get; set; }
    }
}
